apiVersion: v1
kind: ConfigMap
metadata:
  name: dbos-operator
  namespace: dbos-operator
data:
  config.yaml: |
    # DBOS Kubernetes Operator config. Mounted into the pod at /etc/dbos-operator/config.yaml.
    conductor:
      orgName: max
      # endpoint: http://conductor.dbos-conductor.svc.cluster.local:8090
    poller:
      interval: 1s
      maxBackoff: 30s
    apps:
      - name: dbos-k8s-app
    metricsAPI:
      enabled: true
